### ISSUE TITLE
Is there a validation set for EqBen?

### ISSUE THREAD

**Issue by linzhiqiu** [Wangt-CN/EqBen#1]
And why is the zip file so big? Is there a way to reduce its size, eg., downsampling the images? Otherwise it is very costly to conduct experiments on our small server..

**Comment by linzhiqiu** [comment]
Also, is it possible to release the dataset in Winoground format (e.g, each batch is an image_0, image_1, caption_0, caption_1)?

**Comment by Wangt-CN** [comment]
Hi Zhiqiu,

Thanks a lot for your interest in our work. Indeed, our full data annotation is not publicly available. You can use the [annotation file](https://github.com/Wangt-CN/EqBen#1-data-download) and the example code to get the results and upload to the [codalab server](https://codalab.lisn.upsaclay.fr/competitions/10266).

Thanks for letting us know about the huge cost of your server with the current data scale. We are actively working to release a public sub-dataset with label sampling from the full test set (maybe around 20%) in a few days to make it more efficient for visualization and validation.

**Comment by linzhiqiu** [comment]
Thanks for the update! Could you explain what 'private_info' means in your annotation file? Is that the ground truth label?

I think you should be able to convert the images to JPEG format and save a lot of memory without losing performance? 100GB is quite expensive for most academic labs.

**Comment by Wangt-CN** [comment]
Yes, it means the ground truth label.
We have just uploaded the EqBen subset (25K image-text pair) for ease of validation and visualization. Please check it out.

If you have any other questions, feel free to re-open this issue.
