### ISSUE TITLE
Data Download Issue

### ISSUE THREAD

**Issue by quantacode** [Wangt-CN/EqBen#5]
Hi,

I'm interested in testing my model in Eqben but am unable to download the data. I keep getting the following error: 
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>The project to be billed is associated with a delinquent billing account.</Message>
<Details>The billing account for the owning project is disabled in state delinquent</Details>
</Error>

Can you please help resolve the issue?

**Comment by Wangt-CN** [comment]
Hi, thanks for reporting. Could you please try this link: https://drive.google.com/file/d/1e608uhd36ak_v7SnlMVaYcekBc4gBqzn/view?usp=sharing
